spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  jackson:
    property-naming-strategy: SNAKE_CASE

  jwt:
    secret-key: ${SECRET_KEY}
    access-exp: ${ACCESS_EXP}
    refresh-exp: ${REFRESH_EXP}
    header: ${HEADER}
    prefix: ${PREFIX}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_S3_ACCESS}
      secret-key: ${AWS_S3_SECRET}
    region:
      static: ap-northeast-2